create table IOT_DEVICE(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DEVICE_ID VARCHAR(128) NOT NULL,
  ADDRESS TIME WITH TIME ZONE,
  TURNED_ON_AT TIME WITH TIME ZONE,
  TURNED_OFF_AT TIME WITH TIME ZONE,
  CREATED TIME WITH TIME ZONE NOT NULL default CURRENT_TIMESTAMP,
  UPDATED TIME WITH TIME ZONE,
  PRIMARY KEY ( ID )
);

create table IOT_DEVICE_ADDRESS(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128),
  COUNTRY VARCHAR(128) NOT NULL,
  POSTAL_CODE VARCHAR(128) NOT NULL,
  CITY VARCHAR(128) NOT NULL,
  STREET VARCHAR(128) NOT NULL,
  BUILDING_NUMBER VARCHAR(128) NOT NULL,
  APARTMENT_NUMBER VARCHAR(128),
  PRIMARY KEY ( ID )
);

create table IOT_DEVICE_CONFIG(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DEVICE_ID VARCHAR(128) NOT NULL,
  DEVICE_FOREIGN_ID VARCHAR(128) NOT NULL,
  CONFIGURATION JSON(10000) NOT NULL,
  CREATED TIME WITH TIME ZONE NOT NULL default CURRENT_TIMESTAMP,
  UPDATED TIME WITH TIME ZONE,
  PRIMARY KEY ( ID )
);